// Very simple, given an integer or 
// a floating-point number, find its opposite.

// Examples:
// 1: -1
// 14: -14
// -34: 34

// ===================================================================

/* 
PSUEDOCODE:

PROBLEM: I AM GIVEN A NUMBER VALUE AS EITHER POSITIVE OR NEGATIVE
AND I NEED TO RETURN THE OPPOSITE OF THE NUMBER IF ITS NEGATIVE RETURN POSITIVE
IF ITS NEGATIVE RETURN POSITIVE

INPUT: INTERGER OR FLOATING NUM (POSITIVE OR NEGATIVE)
OUTPUT: INTERGER OR FLOAT NUM BUT OPPOSITE VALUE OF THE INPUT 
-- IF ITS NEGATIVE RETURN POSITIVE
-- IF ITS POSITIVE RETURN NEGATIVE

STEPS:
- I FIRST NEED SOMEWAY TO CHECK IF THE INPUT VALUE IS POSITIVE OR NEGATIVE
- CREATE A CONDITIONAL TO CHECK IT 
- INSIDE THE CONDITION IF ITS MET RETURN THE OPPOSITE VALUE

GOOGLE:

*/